import Link from "next/link";
import {Metadata} from "next";
import {Inter} from "next/font/google";
import React, {useEffect} from "react";
import Header from "../Header";
import Footer from "../Footer";
// import AOS from "aos";
// import "aos/dist/aos.css";
import Image from "next/image";

const inter = Inter({subsets: ["latin"]});

// import {headers} from 'next/headers'

import {cookieToInitialState} from 'wagmi'

import {config} from '@/config/config'
import Web3ModalProvider from '@/context'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
                                       children
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    const initialState = cookieToInitialState(config)
    return (
        <>
            <div
                className="w-[56px] h-[56px] fixed bottom-[100px] right-[24px] z-[999] cursor-pointer"
                id="kakao"
                onClick={() => window.open("https://open.kakao.com/o/sabskiZf")}
            >
                <Image src="/kakao.png" fill alt="kakao"/>
            </div>
            <Header/>
            <main
                className={`flex min-h-screen flex-col items-center justify-between pt-[140px]  ${inter.className}`}
            >
                <Web3ModalProvider initialState={initialState}>{children}</Web3ModalProvider>
            </main>
            {/*<Footer />*/}
        </>

    )
}


